### ISSUE TITLE
[DOCS] Suggest README.md Modification

### ISSUE THREAD

**Issue by sree-hari-s** [sree-hari-s/100DaysOfCode-Python#13]
Change the wording of these headings.
- [ ] What is this challenge about?
- [ ] Who can take this challenge?
- [ ] Projects
- [ ] Goals

**Comment by GouraV-Chatterjee** [comment]
Hey...I generated a PR for this issue...Please do take a look

**Comment by sree-hari-s** [comment]
> Hey...I generated a PR for this issue...Please do take a look

when you have raised a PR reference that in an issue also mark the ones you have completed by putting a tick mark.

**Comment by NanduNanduz** [comment]
Please assign me this issue

**Comment by sree-hari-s** [comment]
.take
